### ISSUE TITLE
Mask Annotations

### ISSUE THREAD

**Issue by bruno-krinski** [akTwelve/tutorials#3]
Hi, I'm following your tutorial and it's very good.
The datasets I have been using already has the binary mask in .png format. I'm trying to convert them to the ms-coco format. In some of my images, the object is formed by a list of contours, which generate a list of polygons (multy polygon). My doubt is if in the json annotations, it can be used more than one polygon for each image (in the same annotation, without the need of create a different mask for each image). The followin image shows an example of one of my masks and the polygons.

![example](https://user-images.githubusercontent.com/27218779/45645538-1f22c300-ba97-11e8-8b54-10977f42e814.png)

**Comment by akTwelve** [comment]
Thanks for the compliment! Hopefully I understand your question correctly. If you want to segment multiple objects of the same type, like the sailboats above, you will need to create a different mask for each instance. You can store these masks on disk as different colors in an RGB or even greyscale image, but before converting them to contours, you will need to split them up.

**Comment by Phwanwilai** [comment]
Hi, I'm following your tutorial and it's very good. Good for beginners. I have a question about why Epoch 1/4 takes so long.
![image](https://user-images.githubusercontent.com/33197922/47018700-86f42880-d17f-11e8-85a5-271ab1ac3fba.png)

**Comment by akTwelve** [comment]
@Phwanwilai thanks, glad it's helpful so far. You'd need to give more information for me to guess at why Epoch 1 is slow. How long does it take? Does it eventually finish? If so, is it a lot slower than Epoch 2, 3, and 4?

**Comment by Phwanwilai** [comment]
I waited 3 hours, nothing happened, still pending Epoch 1 and 
The original code from github did not fix anything more.

I use nvidia gpu 1060 ram 6 Gb

thank you

**Comment by akTwelve** [comment]
It should only take a minute to get started. I would try rebooting your machine and trying again. If it still hangs, maybe your computer isn’t powerful enough or the config is not a good fit for your system, but it could be any number of other things.

**Comment by Phwanwilai** [comment]
> It should only take a minute to get started. I would try rebooting your machine and trying again. If it still hangs, maybe your computer isn’t powerful enough or the config is not a good fit for your system, but it could be any number of other things.

thank you 
i am try it

**Comment by Phwanwilai** [comment]
> It should only take a minute to get started. I would try rebooting your machine and trying again. If it still hangs, maybe your computer isn’t powerful enough or the config is not a good fit for your system, but it could be any number of other things.

Thank you for answer!!!!! 

and

i have one question?
I will create a dataset that is my own. What program do I use to create the dataset?
Thank you

![image](https://user-images.githubusercontent.com/33197922/47099414-6d2a1280-d25f-11e8-8905-a94987d8de3b.png)

**Comment by akTwelve** [comment]
Glad it worked! Here’s a tutorial I made that will get you started on creating your own dataset: http://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch

I’m going to consider this issue thread closed. :)

**Comment by Phwanwilai** [comment]
> Glad it worked! Here’s a tutorial I made that will get you started on creating your own dataset: http://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch
> 
> I’m going to consider this issue thread closed. :)

Thank you
