### ISSUE TITLE
Problem in loading json file

### ISSUE THREAD

**Issue by AhmadShaik** [akTwelve/tutorials#4]
`dataset_train = CocoLikeDataset()
dataset_train.load_data('dataset2/train/via_region_data.json', 'dataset2/train')
dataset_train.prepare()

dataset_val = CocoLikeDataset()
dataset_val.load_data('dataset2/val/via_region_data.json', 'dataset2/val')
dataset_val.prepare()`

I am trying to train a model using the json file which is developed based on your tutorial (book, homeplant, bottle). But when I load the training images and annotation json file, I am getting below error. 

> KeyError                                  Traceback (most recent call last)
> <ipython-input-7-572b4a30e8dd> in <module>
>       1 dataset_train = CocoLikeDataset()
> ----> 2 dataset_train.load_data('dataset2/train/via_region_data.json', 'dataset2/train')
>       3 dataset_train.prepare()
>       4 
>       5 dataset_val = CocoLikeDataset()
> 
> <ipython-input-6-5aee722e418a> in load_data(self, annotation_json, images_dir)
>      16         # Add the class names using the base method from utils.Dataset
>      17         source_name = "coco_like"
> ---> 18         for category in coco_json['categories']:
>      19             class_id = category['id']
>      20             class_name = category['name']
> 
> KeyError: 'categories'

**Comment by akTwelve** [comment]
Hey @AhmadShaik, I'm really sorry I didn't see this until now. My github emails were being sent to my spam folder. Hopefully you've already solved your problem by now, but if not, it looks like a pretty straightforward error. Your JSON file needs a 'categories' section. You may find this video helpful: https://youtu.be/h6s61a_pqfM
