### ISSUE TITLE
InvalidArgumentError: Incompatible shapes: [1,38,26,256] vs. [1,38,25,256]

### ISSUE THREAD

**Issue by rsumit123** [akTwelve/tutorials#6]
Hey thanks so much for helping to load Coco-like datasets into the model. However i am running into this error while executing the code from your notebook . I am training the code on ModaNet database and i am running into the following error.

`---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-39-b8b3d5708867> in <module>
      3             learning_rate=config.LEARNING_RATE,
      4             epochs=4,
----> 5             layers='heads',augmentation=augmentation)
      6 end_train = time.time()
      7 minutes = round((end_train - start_train) / 60, 2)

~/modanet_segmentation/segmentation/mrcnn/model.py in train(self, train_dataset, val_dataset, learning_rate, epochs, layers, augmentation, custom_callbacks, no_augmentation_sources)
   2375             max_queue_size=100,
   2376             workers=workers,
-> 2377             use_multiprocessing=True,
   2378         )
   2379         self.epoch = max(self.epoch, epochs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/envs/python3/lib/python3.6/site-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1416             use_multiprocessing=use_multiprocessing,
   1417             shuffle=shuffle,
-> 1418             initial_epoch=initial_epoch)
   1419 
   1420     @interfaces.legacy_generator_methods_support

~/anaconda3/envs/python3/lib/python3.6/site-packages/keras/engine/training_generator.py in fit_generator(model, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
    215                 outs = model.train_on_batch(x, y,
    216                                             sample_weight=sample_weight,
--> 217                                             class_weight=class_weight)
    218 
    219                 outs = to_list(outs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1215             ins = x + y + sample_weights
   1216         self._make_train_function()
-> 1217         outputs = self.train_function(ins)
   1218         return unpack_singleton(outputs)
   1219 

~/anaconda3/envs/python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2713                 return self._legacy_call(inputs)
   2714 
-> 2715             return self._call(inputs)
   2716         else:
   2717             if py_any(is_tensor(x) for x in inputs):

~/anaconda3/envs/python3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2673             fetched = self._callable_fn(*array_vals, run_metadata=self.run_metadata)
   2674         else:
-> 2675             fetched = self._callable_fn(*array_vals)
   2676         return fetched[:len(self.outputs)]
   2677 

~/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/client/session.py in __call__(self, *args, **kwargs)
   1456         ret = tf_session.TF_SessionRunCallable(self._session._session,
   1457                                                self._handle, args,
-> 1458                                                run_metadata_ptr)
   1459         if run_metadata:
   1460           proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

InvalidArgumentError: Incompatible shapes: [1,38,26,256] vs. [1,38,25,256]
	 [[{{node training_2/SGD/gradients/fpn_p4add_1/add_grad/BroadcastGradientArgs}}]]`

Can you help me understand this ?

**Comment by akTwelve** [comment]
Sorry, I can't figure this one out. Really hard to understand from the error message. You'd probably have better luck asking on the Mask R-CNN repo.
